import type { DestinationSlug } from '../content/destinations';
import type { ServiceSlug } from '../content/services';
import type { ExperienceSlug } from '../content/experiences';
import type { ProjectSlug } from './site';

export interface EventType {
  slug: string;
  name: string;
  tagline: string;
  description: string;
  image: string;
  icon: string;
  destinations: DestinationSlug[];
  services: ServiceSlug[];
  experiences: ExperienceSlug[];
  projects: ProjectSlug[];
}

export const IMAGES = {
  heroEvents: "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/81/Drummer_at_Tour_DU_rwanda_2024.jpg/1280px-Drummer_at_Tour_DU_rwanda_2024.jpg",
  gorillas: "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/de/Mountain_gorilla_from_Susa_Group_in_Karisimbi_thicket_of_Volcanoes_National_Park_in_Rwanda._Emmanuel_Kwizera.jpg/3840px-Mountain_gorilla_from_Susa_Group_in_Karisimbi_thicket_of_Volcanoes_National_Park_in_Rwanda._Emmanuel_Kwizera.jpg",
  forest: "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/02/Nyungwe_Forest_NP_20150928-DSCF4880.jpg/3840px-Nyungwe_Forest_NP_20150928-DSCF4880.jpg",
  lake: "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/8a/Lake_Kivu_at_dawn.jpg/1920px-Lake_Kivu_at_dawn.jpg",
  tea: "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/94/Tea_plantation%2C_Western_Rwanda.jpg/3840px-Tea_plantation%2C_Western_Rwanda.jpg",
  wedding: "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/1f/Rwanda_tradional_dance_in_wedding.jpg/3840px-Rwanda_tradional_dance_in_wedding.jpg",
  birthday: "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/3a/RWANDAN_CHILDREN_PLAYING.jpg/3840px-RWANDAN_CHILDREN_PLAYING.jpg",
  graduation: "https://thumb.wikimedia.org/wikipedia/commons/thumb/b/ba/Intore_dancer_during_the_graduation_festivities_at_Kicukiro_stadium_in_Rwanda.jpg/3840px-Intore_dancer_during_the_graduation_festivities_at_Kicukiro_stadium_in_Rwanda.jpg",
  corporate: "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/43/An_aerial_of_Kigali_Convention_Center_on_June_19%2C_2019._Photo_by_Emmanuel_Kwizera.jpg/3840px-An_aerial_of_Kigali_Convention_Center_on_June_19%2C_2019._Photo_by_Emmanuel_Kwizera.jpg",
  entertainment: "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/dc/Intore_Performance.jpg/1920px-Intore_Performance.jpg",
  sports: "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/49/Tour_DU_rwanda_2024.jpg/1280px-Tour_DU_rwanda_2024.jpg",
  cultural: "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/fe/Intore_mu_Rwanda.jpg/1920px-Intore_mu_Rwanda.jpg",
  religious: "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/75/ASC_Leiden_-_Rwanda_2021_-_027_-_A_church_service_in_a_modern_church_-_Kigali.jpg/1920px-ASC_Leiden_-_Rwanda_2021_-_027_-_A_church_service_in_a_modern_church_-_Kigali.jpg",
  social: "https://upload.wikimedia.org/wikipedia/commons/4/41/Kimironko_Market%2C_Kigali.jpg",
  award: "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c6/Rwandan_wedding_stage.jpg/1920px-Rwandan_wedding_stage.jpg",
  exhibition: "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/81/Kigali_Convention_Center_outside_parking_and_compound.jpg/3840px-Kigali_Convention_Center_outside_parking_and_compound.jpg",
  national: "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/ca/Amahoro_Stadium_Kigali.jpg/1920px-Amahoro_Stadium_Kigali.jpg",
  charity: "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f9/Umuganda.jpg/3840px-Umuganda.jpg",
  educational: "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/cd/University_students_in_meeting_when_schools_resumed_after_Covid-19_lockdown_in_Rwanda.jpg/1920px-University_students_in_meeting_when_schools_resumed_after_Covid-19_lockdown_in_Rwanda.jpg",
  mountains: "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/cd/Mt_kalisimbi%2C_Nyamuragira_and_Bisoke_sunset_view.jpg/3840px-Mt_kalisimbi%2C_Nyamuragira_and_Bisoke_sunset_view.jpg",
  stage: "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/fe/Intore_mu_Rwanda.jpg/1920px-Intore_mu_Rwanda.jpg",
  team: "https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e7/Launch_of_the_Environment_Week_2017-_Umuganda_at_Nyandungu_Wetland_-_34961808125.jpg/3840px-Launch_of_the_Environment_Week_2017-_Umuganda_at_Nyandungu_Wetland_-_34961808125.jpg",
  solar: "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/23/Sunset_views_from_Nyamirambo.jpg/3840px-Sunset_views_from_Nyamirambo.jpg",
  catering: "https://upload.wikimedia.org/wikipedia/commons/9/90/Traditional_food_from_Rwanda.jpg",
  woman: "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/1c/Rwandan_basket_weaving.jpg/3840px-Rwandan_basket_weaving.jpg",
  conference: "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/48/Kigali_Convention_Centre.jpg/1280px-Kigali_Convention_Centre.jpg",
} as const;

export const EVENT_TYPES: EventType[] = [
  {
    slug: "birthday",
    name: "Birthday Events",
    tagline: "Unforgettable celebrations for every age",
    description: "From milestone children's parties to grand 50th celebrations, we design birthday events around your story — themed decor, gourmet catering, live music, and venues across Rwanda's finest locations.",
    image: IMAGES.birthday,
    icon: "cake",
    destinations: ["kigali", "lake-kivu"],
    services: ["bespoke-itinerary", "catering-hospitality", "private-transport", "production-media"],
    experiences: ["gourmet-catering", "agaseke-weaving"],
    projects: ["nyamirambo-solar"],
  },
  {
    slug: "wedding",
    name: "Wedding Events",
    tagline: "Say 'I do' beneath a thousand hills",
    description: "Traditional and modern Rwandan weddings, civil unions, and holy matrimony. We manage the full journey — ceremony styling, catering, entertainment, guest transport, and breathtaking lakeside or volcano-view backdrops.",
    image: IMAGES.wedding,
    icon: "favorite",
    destinations: ["lake-kivu", "musanze", "kigali"],
    services: ["bespoke-itinerary", "catering-hospitality", "venue-style", "private-transport"],
    experiences: ["gourmet-catering", "intore-dance", "agaseke-weaving"],
    projects: ["kivu-wedding"],
  },
  {
    slug: "graduation",
    name: "Graduation Events",
    tagline: "Honour the achievement, launch the future",
    description: "Graduation parties and ceremonies complete with photographers, celebratory dining, family transport, and venue styling — so the graduate's big day runs without a single hiccup.",
    image: IMAGES.graduation,
    icon: "school",
    destinations: ["kigali", "lake-kivu"],
    services: ["bespoke-itinerary", "catering-hospitality", "private-transport", "production-media"],
    experiences: ["gourmet-catering"],
    projects: ["kivu-coffee"],
  },
  {
    slug: "corporate",
    name: "Corporate Events",
    tagline: "Meetings, retreats, and team building that deliver",
    description: "Board retreats, product launches, conferences, and incentive trips. We handle the logistics — venues, AV production, transport fleets, catering, and high-impact team-building programs — so your team stays focused on outcomes.",
    image: IMAGES.corporate,
    icon: "business_center",
    destinations: ["kigali", "musanze", "gishwati-mukura"],
    services: ["corporate-group-travel", "private-transport", "luxury-lodge-booking", "production-media"],
    experiences: ["team-building", "canopy-walk", "gourmet-catering"],
    projects: ["corporate-summit"],
  },
  {
    slug: "entertainment",
    name: "Entertainment Events",
    tagline: "Concerts, festivals, and shows people talk about",
    description: "From acoustic evenings by Lake Kivu to multi-stage festivals in Kigali, we produce entertainment events end-to-end — sound and lighting, artist logistics, ticketing support, and food & beverage.",
    image: IMAGES.entertainment,
    icon: "music_note",
    destinations: ["kigali", "lake-kivu"],
    services: ["production-media", "venue-style", "private-transport", "catering-hospitality"],
    experiences: ["intore-dance", "gourmet-catering"],
    projects: ["kivu-coffee"],
  },
  {
    slug: "sports",
    name: "Sports Events",
    tagline: "Tournaments, marathons, and active challenges",
    description: "Charity runs, cycling races on the Congo Nile Trail, corporate sports days, and adventure tournaments. We coordinate permits, safety, medical cover, hydration stations, and awards.",
    image: IMAGES.sports,
    icon: "sports_soccer",
    destinations: ["musanze", "kigali", "nyungwe"],
    services: ["permits-safety", "private-transport", "catering-hospitality", "production-media"],
    experiences: ["team-building", "canopy-walk"],
    projects: ["akagera-lions"],
  },
  {
    slug: "cultural",
    name: "Cultural Events",
    tagline: "Celebrate the heartbeat of Rwanda",
    description: "Intore dance performances, craft markets, traditional ceremonies, and heritage festivals. We partner with local cooperatives so every cultural event directly supports the communities that keep these traditions alive.",
    image: IMAGES.cultural,
    icon: "festival",
    destinations: ["musanze", "kigali", "nyungwe"],
    services: ["community-cultural-tours", "bespoke-itinerary", "production-media"],
    experiences: ["agaseke-weaving", "intore-dance", "umuganda-day"],
    projects: ["nyamirambo-solar"],
  },
  {
    slug: "religious",
    name: "Religious Events",
    tagline: "Sacred moments, meticulously arranged",
    description: "Weddings, baptisms, church conferences, crusades, and interfaith gatherings. We bring dignified venue styling, hospitality, and logistics that let you focus on the spiritual meaning of the occasion.",
    image: IMAGES.religious,
    icon: "church",
    destinations: ["kigali", "lake-kivu"],
    services: ["bespoke-itinerary", "catering-hospitality", "venue-style", "private-transport"],
    experiences: ["gourmet-catering", "umuganda-day"],
    projects: ["nyamirambo-solar"],
  },
  {
    slug: "social",
    name: "Social Events",
    tagline: "Reunions, house parties, and quality time",
    description: "Family reunions, anniversaries, baby showers, and relaxed get-togethers. We create warm, effortless experiences with catering, styling, and local entertainment tailored to your guest list.",
    image: IMAGES.social,
    icon: "celebration",
    destinations: ["lake-kivu", "kigali"],
    services: ["catering-hospitality", "private-transport", "venue-style"],
    experiences: ["gourmet-catering", "agaseke-weaving"],
    projects: ["kivu-coffee"],
  },
  {
    slug: "award",
    name: "Award Events",
    tagline: "Ceremonies that honour excellence",
    description: "Award ceremonies, gala dinners, and recognition nights. We manage red carpets, stages, trophies, media, and guest experiences to make every winner feel celebrated.",
    image: IMAGES.award,
    icon: "workspace_premium",
    destinations: ["kigali"],
    services: ["production-media", "bespoke-itinerary", "private-transport", "catering-hospitality"],
    experiences: ["gourmet-catering", "intore-dance"],
    projects: ["charity-gala", "kivu-coffee"],
  },
  {
    slug: "exhibitions-trade",
    name: "Exhibitions & Trade Fairs",
    tagline: "Showcase, connect, and do business",
    description: "Trade exhibitions, product launches, and fairs in Rwanda's premier venues. We coordinate booth logistics, brand activations, guests, and the little details that make your stand impossible to pass.",
    image: IMAGES.exhibition,
    icon: "storefront",
    destinations: ["kigali"],
    services: ["production-media", "venue-style", "private-transport", "corporate-group-travel"],
    experiences: ["crop-to-cup", "gourmet-catering"],
    projects: ["kivu-coffee"],
  },
  {
    slug: "tourism",
    name: "Tourism Events",
    tagline: "Group tours, safaris, and hosted travel",
    description: "Fam trips, hosted traveler events, and curated group excursions. From gorilla trekking to coffee circuits, we design tourism events that showcase the very best of Rwanda to your guests.",
    image: IMAGES.mountains,
    icon: "travel_explore",
    destinations: ["musanze", "nyungwe", "lake-kivu", "gishwati-mukura", "kigali"],
    services: ["gorilla-permits", "luxury-lodge-booking", "private-transport", "bespoke-itinerary"],
    experiences: ["crop-to-cup", "canopy-walk", "agaseke-weaving"],
    projects: ["akagera-lions", "kivu-coffee"],
  },
  {
    slug: "national-public",
    name: "National & Public Events",
    tagline: "Patriotic gatherings and city-wide moments",
    description: "National holidays, liberation days, public festivals, and civic ceremonies. We deliver secure, organized, and memorable public events at scale — always respectful of Rwanda's history and pride.",
    image: IMAGES.national,
    icon: "flag",
    destinations: ["kigali", "musanze"],
    services: ["production-media", "permits-safety", "private-transport"],
    experiences: ["umuganda-day", "intore-dance"],
    projects: ["nyamirambo-solar"],
  },
  {
    slug: "fundraising-charity",
    name: "Fundraising & Charity Events",
    tagline: "Good causes deserve great events",
    description: "Charity galas, auctions, sponsorships, and community drives. We help you raise more for your mission with impactful staging, storytelling, and hospitality — and we connect causes with our community partners.",
    image: IMAGES.charity,
    icon: "volunteer_activism",
    destinations: ["kigali", "lake-kivu"],
    services: ["production-media", "catering-hospitality", "private-transport", "bespoke-itinerary"],
    experiences: ["umuganda-day", "gourmet-catering", "intore-dance"],
    projects: ["charity-gala", "nyamirambo-solar"],
  },
  {
    slug: "educational",
    name: "Educational Events",
    tagline: "Workshops, field trips, and learning festivals",
    description: "School excursions, university study tours, workshops, and training academies. We marry classroom goals with unforgettable field learning in Rwanda's national parks, farms, and craft cooperatives.",
    image: IMAGES.educational,
    icon: "menu_book",
    destinations: ["nyungwe", "gishwati-mukura", "kigali"],
    services: ["corporate-group-travel", "private-transport", "bespoke-itinerary"],
    experiences: ["canopy-walk", "crop-to-cup", "umuganda-day"],
    projects: ["gorilla-vet", "kivu-coffee"],
  },
];

export const eventsFor = (kind: 'destinations' | 'services' | 'experiences' | 'projects', slug: string): EventType[] =>
  EVENT_TYPES.filter((event) => (event[kind] as readonly string[]).includes(slug));

export const EVENT_BY_SLUG = Object.fromEntries(EVENT_TYPES.map((e) => [e.slug, e])) as Record<string, EventType>;